project_id = "bkkluziuyystiqkcpbnd"

[functions.process-leaderboard-rewards]
verify_jwt = false

[functions.generate-weekly-challenges]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-cat-portrait]
verify_jwt = false
