/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminChatRouteImport } from './routes/admin-chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as EmpireRouteImport } from './routes/empire'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as CatkingIndexRouteImport } from './routes/catking/index'
import { Route as CatkingActivityRouteImport } from './routes/catking/activity'
import { Route as CatkingAiMetricsRouteImport } from './routes/catking/ai-metrics'
import { Route as CatkingAnnouncementsRouteImport } from './routes/catking/announcements'
import { Route as CatkingBattlePassRouteImport } from './routes/catking/battle-pass'
import { Route as CatkingConfigRouteImport } from './routes/catking/config'
import { Route as CatkingDashboardRouteImport } from './routes/catking/dashboard'
import { Route as CatkingDocsRouteImport } from './routes/catking/docs'
import { Route as CatkingErrorsRouteImport } from './routes/catking/errors'
import { Route as CatkingGameRepairRouteImport } from './routes/catking/game-repair'
import { Route as CatkingMessagesRouteImport } from './routes/catking/messages'
import { Route as CatkingModerationRouteImport } from './routes/catking/moderation'
import { Route as CatkingNotificationsRouteImport } from './routes/catking/notifications'
import { Route as CatkingPayloadValidatorRouteImport } from './routes/catking/payload-validator'
import { Route as CatkingProfilesRouteImport } from './routes/catking/profiles'
import { Route as CatkingSaveRecoveryRouteImport } from './routes/catking/save-recovery'
import { Route as CatkingScheduledJobsRouteImport } from './routes/catking/scheduled-jobs'
import { Route as CatkingSecurityRouteImport } from './routes/catking/security'
import { Route as CatkingSettingsRouteImport } from './routes/catking/settings'
import { Route as CatkingStatsRouteImport } from './routes/catking/stats'
import { Route as CatkingTelemetryRouteImport } from './routes/catking/telemetry'
import { Route as CatkingTestsRouteImport } from './routes/catking/tests'
import { Route as CatkingTrackingRouteImport } from './routes/catking/tracking'
import { Route as CatkingTutorialRouteImport } from './routes/catking/tutorial'
import { Route as CatkingUsersRouteImport } from './routes/catking/users'
import { Route as CatkingWinstonRouteImport } from './routes/catking/winston'
import { Route as CustomizeIndexRouteImport } from './routes/customize/index'
import { Route as CustomizeCatIdRouteImport } from './routes/customize/$catId'
import { Route as PhotoboothIndexRouteImport } from './routes/photobooth/index'
import { Route as PhotoboothCatIdRouteImport } from './routes/photobooth/$catId'
import { Route as ApiPublicJobsCleanupErrorLogsRouteImport } from './routes/api/public/jobs/cleanup-error-logs'
import { Route as ApiPublicJobsGenerateWeeklyChallengesRouteImport } from './routes/api/public/jobs/generate-weekly-challenges'
import { Route as ApiPublicJobsProcessLeaderboardRewardsRouteImport } from './routes/api/public/jobs/process-leaderboard-rewards'
import { Route as ApiPublicJobsSendAdminAlertRouteImport } from './routes/api/public/jobs/send-admin-alert'
import { Route as ApiPublicJobsSyncHealthCheckRouteImport } from './routes/api/public/jobs/sync-health-check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin-chat',
  path: '/admin-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpireRoute = EmpireRouteImport.update({
  id: '/empire',
  path: '/empire',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingIndexRoute = CatkingIndexRouteImport.update({
  id: '/catking/',
  path: '/catking/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingActivityRoute = CatkingActivityRouteImport.update({
  id: '/catking/activity',
  path: '/catking/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingAiMetricsRoute = CatkingAiMetricsRouteImport.update({
  id: '/catking/ai-metrics',
  path: '/catking/ai-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingAnnouncementsRoute = CatkingAnnouncementsRouteImport.update({
  id: '/catking/announcements',
  path: '/catking/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingBattlePassRoute = CatkingBattlePassRouteImport.update({
  id: '/catking/battle-pass',
  path: '/catking/battle-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingConfigRoute = CatkingConfigRouteImport.update({
  id: '/catking/config',
  path: '/catking/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingDashboardRoute = CatkingDashboardRouteImport.update({
  id: '/catking/dashboard',
  path: '/catking/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingDocsRoute = CatkingDocsRouteImport.update({
  id: '/catking/docs',
  path: '/catking/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingErrorsRoute = CatkingErrorsRouteImport.update({
  id: '/catking/errors',
  path: '/catking/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingGameRepairRoute = CatkingGameRepairRouteImport.update({
  id: '/catking/game-repair',
  path: '/catking/game-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingMessagesRoute = CatkingMessagesRouteImport.update({
  id: '/catking/messages',
  path: '/catking/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingModerationRoute = CatkingModerationRouteImport.update({
  id: '/catking/moderation',
  path: '/catking/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingNotificationsRoute = CatkingNotificationsRouteImport.update({
  id: '/catking/notifications',
  path: '/catking/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingPayloadValidatorRoute = CatkingPayloadValidatorRouteImport.update({
  id: '/catking/payload-validator',
  path: '/catking/payload-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingProfilesRoute = CatkingProfilesRouteImport.update({
  id: '/catking/profiles',
  path: '/catking/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingSaveRecoveryRoute = CatkingSaveRecoveryRouteImport.update({
  id: '/catking/save-recovery',
  path: '/catking/save-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingScheduledJobsRoute = CatkingScheduledJobsRouteImport.update({
  id: '/catking/scheduled-jobs',
  path: '/catking/scheduled-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingSecurityRoute = CatkingSecurityRouteImport.update({
  id: '/catking/security',
  path: '/catking/security',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingSettingsRoute = CatkingSettingsRouteImport.update({
  id: '/catking/settings',
  path: '/catking/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingStatsRoute = CatkingStatsRouteImport.update({
  id: '/catking/stats',
  path: '/catking/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingTelemetryRoute = CatkingTelemetryRouteImport.update({
  id: '/catking/telemetry',
  path: '/catking/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingTestsRoute = CatkingTestsRouteImport.update({
  id: '/catking/tests',
  path: '/catking/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingTrackingRoute = CatkingTrackingRouteImport.update({
  id: '/catking/tracking',
  path: '/catking/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingTutorialRoute = CatkingTutorialRouteImport.update({
  id: '/catking/tutorial',
  path: '/catking/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingUsersRoute = CatkingUsersRouteImport.update({
  id: '/catking/users',
  path: '/catking/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CatkingWinstonRoute = CatkingWinstonRouteImport.update({
  id: '/catking/winston',
  path: '/catking/winston',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeIndexRoute = CustomizeIndexRouteImport.update({
  id: '/customize/',
  path: '/customize/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeCatIdRoute = CustomizeCatIdRouteImport.update({
  id: '/customize/$catId',
  path: '/customize/$catId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoboothIndexRoute = PhotoboothIndexRouteImport.update({
  id: '/photobooth/',
  path: '/photobooth/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoboothCatIdRoute = PhotoboothCatIdRouteImport.update({
  id: '/photobooth/$catId',
  path: '/photobooth/$catId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsCleanupErrorLogsRoute =
  ApiPublicJobsCleanupErrorLogsRouteImport.update({
    id: '/api/public/jobs/cleanup-error-logs',
    path: '/api/public/jobs/cleanup-error-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsGenerateWeeklyChallengesRoute =
  ApiPublicJobsGenerateWeeklyChallengesRouteImport.update({
    id: '/api/public/jobs/generate-weekly-challenges',
    path: '/api/public/jobs/generate-weekly-challenges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsProcessLeaderboardRewardsRoute =
  ApiPublicJobsProcessLeaderboardRewardsRouteImport.update({
    id: '/api/public/jobs/process-leaderboard-rewards',
    path: '/api/public/jobs/process-leaderboard-rewards',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsSendAdminAlertRoute =
  ApiPublicJobsSendAdminAlertRouteImport.update({
    id: '/api/public/jobs/send-admin-alert',
    path: '/api/public/jobs/send-admin-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsSyncHealthCheckRoute =
  ApiPublicJobsSyncHealthCheckRouteImport.update({
    id: '/api/public/jobs/sync-health-check',
    path: '/api/public/jobs/sync-health-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-chat': typeof AdminChatRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/empire': typeof EmpireRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/portal': typeof PortalRoute
  '/relationships': typeof RelationshipsRoute
  '/stats': typeof StatsRoute
  '/catking/activity': typeof CatkingActivityRoute
  '/catking/ai-metrics': typeof CatkingAiMetricsRoute
  '/catking/announcements': typeof CatkingAnnouncementsRoute
  '/catking/battle-pass': typeof CatkingBattlePassRoute
  '/catking/config': typeof CatkingConfigRoute
  '/catking/dashboard': typeof CatkingDashboardRoute
  '/catking/docs': typeof CatkingDocsRoute
  '/catking/errors': typeof CatkingErrorsRoute
  '/catking/game-repair': typeof CatkingGameRepairRoute
  '/catking/messages': typeof CatkingMessagesRoute
  '/catking/moderation': typeof CatkingModerationRoute
  '/catking/notifications': typeof CatkingNotificationsRoute
  '/catking/payload-validator': typeof CatkingPayloadValidatorRoute
  '/catking/profiles': typeof CatkingProfilesRoute
  '/catking/save-recovery': typeof CatkingSaveRecoveryRoute
  '/catking/scheduled-jobs': typeof CatkingScheduledJobsRoute
  '/catking/security': typeof CatkingSecurityRoute
  '/catking/settings': typeof CatkingSettingsRoute
  '/catking/stats': typeof CatkingStatsRoute
  '/catking/telemetry': typeof CatkingTelemetryRoute
  '/catking/tests': typeof CatkingTestsRoute
  '/catking/tracking': typeof CatkingTrackingRoute
  '/catking/tutorial': typeof CatkingTutorialRoute
  '/catking/users': typeof CatkingUsersRoute
  '/catking/winston': typeof CatkingWinstonRoute
  '/customize/$catId': typeof CustomizeCatIdRoute
  '/photobooth/$catId': typeof PhotoboothCatIdRoute
  '/catking/': typeof CatkingIndexRoute
  '/customize/': typeof CustomizeIndexRoute
  '/photobooth/': typeof PhotoboothIndexRoute
  '/api/public/jobs/cleanup-error-logs': typeof ApiPublicJobsCleanupErrorLogsRoute
  '/api/public/jobs/generate-weekly-challenges': typeof ApiPublicJobsGenerateWeeklyChallengesRoute
  '/api/public/jobs/process-leaderboard-rewards': typeof ApiPublicJobsProcessLeaderboardRewardsRoute
  '/api/public/jobs/send-admin-alert': typeof ApiPublicJobsSendAdminAlertRoute
  '/api/public/jobs/sync-health-check': typeof ApiPublicJobsSyncHealthCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-chat': typeof AdminChatRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/empire': typeof EmpireRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/portal': typeof PortalRoute
  '/relationships': typeof RelationshipsRoute
  '/stats': typeof StatsRoute
  '/catking/activity': typeof CatkingActivityRoute
  '/catking/ai-metrics': typeof CatkingAiMetricsRoute
  '/catking/announcements': typeof CatkingAnnouncementsRoute
  '/catking/battle-pass': typeof CatkingBattlePassRoute
  '/catking/config': typeof CatkingConfigRoute
  '/catking/dashboard': typeof CatkingDashboardRoute
  '/catking/docs': typeof CatkingDocsRoute
  '/catking/errors': typeof CatkingErrorsRoute
  '/catking/game-repair': typeof CatkingGameRepairRoute
  '/catking/messages': typeof CatkingMessagesRoute
  '/catking/moderation': typeof CatkingModerationRoute
  '/catking/notifications': typeof CatkingNotificationsRoute
  '/catking/payload-validator': typeof CatkingPayloadValidatorRoute
  '/catking/profiles': typeof CatkingProfilesRoute
  '/catking/save-recovery': typeof CatkingSaveRecoveryRoute
  '/catking/scheduled-jobs': typeof CatkingScheduledJobsRoute
  '/catking/security': typeof CatkingSecurityRoute
  '/catking/settings': typeof CatkingSettingsRoute
  '/catking/stats': typeof CatkingStatsRoute
  '/catking/telemetry': typeof CatkingTelemetryRoute
  '/catking/tests': typeof CatkingTestsRoute
  '/catking/tracking': typeof CatkingTrackingRoute
  '/catking/tutorial': typeof CatkingTutorialRoute
  '/catking/users': typeof CatkingUsersRoute
  '/catking/winston': typeof CatkingWinstonRoute
  '/customize/$catId': typeof CustomizeCatIdRoute
  '/photobooth/$catId': typeof PhotoboothCatIdRoute
  '/catking': typeof CatkingIndexRoute
  '/customize': typeof CustomizeIndexRoute
  '/photobooth': typeof PhotoboothIndexRoute
  '/api/public/jobs/cleanup-error-logs': typeof ApiPublicJobsCleanupErrorLogsRoute
  '/api/public/jobs/generate-weekly-challenges': typeof ApiPublicJobsGenerateWeeklyChallengesRoute
  '/api/public/jobs/process-leaderboard-rewards': typeof ApiPublicJobsProcessLeaderboardRewardsRoute
  '/api/public/jobs/send-admin-alert': typeof ApiPublicJobsSendAdminAlertRoute
  '/api/public/jobs/sync-health-check': typeof ApiPublicJobsSyncHealthCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-chat': typeof AdminChatRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/empire': typeof EmpireRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/portal': typeof PortalRoute
  '/relationships': typeof RelationshipsRoute
  '/stats': typeof StatsRoute
  '/catking/activity': typeof CatkingActivityRoute
  '/catking/ai-metrics': typeof CatkingAiMetricsRoute
  '/catking/announcements': typeof CatkingAnnouncementsRoute
  '/catking/battle-pass': typeof CatkingBattlePassRoute
  '/catking/config': typeof CatkingConfigRoute
  '/catking/dashboard': typeof CatkingDashboardRoute
  '/catking/docs': typeof CatkingDocsRoute
  '/catking/errors': typeof CatkingErrorsRoute
  '/catking/game-repair': typeof CatkingGameRepairRoute
  '/catking/messages': typeof CatkingMessagesRoute
  '/catking/moderation': typeof CatkingModerationRoute
  '/catking/notifications': typeof CatkingNotificationsRoute
  '/catking/payload-validator': typeof CatkingPayloadValidatorRoute
  '/catking/profiles': typeof CatkingProfilesRoute
  '/catking/save-recovery': typeof CatkingSaveRecoveryRoute
  '/catking/scheduled-jobs': typeof CatkingScheduledJobsRoute
  '/catking/security': typeof CatkingSecurityRoute
  '/catking/settings': typeof CatkingSettingsRoute
  '/catking/stats': typeof CatkingStatsRoute
  '/catking/telemetry': typeof CatkingTelemetryRoute
  '/catking/tests': typeof CatkingTestsRoute
  '/catking/tracking': typeof CatkingTrackingRoute
  '/catking/tutorial': typeof CatkingTutorialRoute
  '/catking/users': typeof CatkingUsersRoute
  '/catking/winston': typeof CatkingWinstonRoute
  '/customize/$catId': typeof CustomizeCatIdRoute
  '/photobooth/$catId': typeof PhotoboothCatIdRoute
  '/catking/': typeof CatkingIndexRoute
  '/customize/': typeof CustomizeIndexRoute
  '/photobooth/': typeof PhotoboothIndexRoute
  '/api/public/jobs/cleanup-error-logs': typeof ApiPublicJobsCleanupErrorLogsRoute
  '/api/public/jobs/generate-weekly-challenges': typeof ApiPublicJobsGenerateWeeklyChallengesRoute
  '/api/public/jobs/process-leaderboard-rewards': typeof ApiPublicJobsProcessLeaderboardRewardsRoute
  '/api/public/jobs/send-admin-alert': typeof ApiPublicJobsSendAdminAlertRoute
  '/api/public/jobs/sync-health-check': typeof ApiPublicJobsSyncHealthCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-chat'
    | '/auth'
    | '/collection'
    | '/empire'
    | '/gallery'
    | '/leaderboard'
    | '/messages'
    | '/portal'
    | '/relationships'
    | '/stats'
    | '/catking/activity'
    | '/catking/ai-metrics'
    | '/catking/announcements'
    | '/catking/battle-pass'
    | '/catking/config'
    | '/catking/dashboard'
    | '/catking/docs'
    | '/catking/errors'
    | '/catking/game-repair'
    | '/catking/messages'
    | '/catking/moderation'
    | '/catking/notifications'
    | '/catking/payload-validator'
    | '/catking/profiles'
    | '/catking/save-recovery'
    | '/catking/scheduled-jobs'
    | '/catking/security'
    | '/catking/settings'
    | '/catking/stats'
    | '/catking/telemetry'
    | '/catking/tests'
    | '/catking/tracking'
    | '/catking/tutorial'
    | '/catking/users'
    | '/catking/winston'
    | '/customize/$catId'
    | '/photobooth/$catId'
    | '/catking/'
    | '/customize/'
    | '/photobooth/'
    | '/api/public/jobs/cleanup-error-logs'
    | '/api/public/jobs/generate-weekly-challenges'
    | '/api/public/jobs/process-leaderboard-rewards'
    | '/api/public/jobs/send-admin-alert'
    | '/api/public/jobs/sync-health-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-chat'
    | '/auth'
    | '/collection'
    | '/empire'
    | '/gallery'
    | '/leaderboard'
    | '/messages'
    | '/portal'
    | '/relationships'
    | '/stats'
    | '/catking/activity'
    | '/catking/ai-metrics'
    | '/catking/announcements'
    | '/catking/battle-pass'
    | '/catking/config'
    | '/catking/dashboard'
    | '/catking/docs'
    | '/catking/errors'
    | '/catking/game-repair'
    | '/catking/messages'
    | '/catking/moderation'
    | '/catking/notifications'
    | '/catking/payload-validator'
    | '/catking/profiles'
    | '/catking/save-recovery'
    | '/catking/scheduled-jobs'
    | '/catking/security'
    | '/catking/settings'
    | '/catking/stats'
    | '/catking/telemetry'
    | '/catking/tests'
    | '/catking/tracking'
    | '/catking/tutorial'
    | '/catking/users'
    | '/catking/winston'
    | '/customize/$catId'
    | '/photobooth/$catId'
    | '/catking'
    | '/customize'
    | '/photobooth'
    | '/api/public/jobs/cleanup-error-logs'
    | '/api/public/jobs/generate-weekly-challenges'
    | '/api/public/jobs/process-leaderboard-rewards'
    | '/api/public/jobs/send-admin-alert'
    | '/api/public/jobs/sync-health-check'
  id:
    | '__root__'
    | '/'
    | '/admin-chat'
    | '/auth'
    | '/collection'
    | '/empire'
    | '/gallery'
    | '/leaderboard'
    | '/messages'
    | '/portal'
    | '/relationships'
    | '/stats'
    | '/catking/activity'
    | '/catking/ai-metrics'
    | '/catking/announcements'
    | '/catking/battle-pass'
    | '/catking/config'
    | '/catking/dashboard'
    | '/catking/docs'
    | '/catking/errors'
    | '/catking/game-repair'
    | '/catking/messages'
    | '/catking/moderation'
    | '/catking/notifications'
    | '/catking/payload-validator'
    | '/catking/profiles'
    | '/catking/save-recovery'
    | '/catking/scheduled-jobs'
    | '/catking/security'
    | '/catking/settings'
    | '/catking/stats'
    | '/catking/telemetry'
    | '/catking/tests'
    | '/catking/tracking'
    | '/catking/tutorial'
    | '/catking/users'
    | '/catking/winston'
    | '/customize/$catId'
    | '/photobooth/$catId'
    | '/catking/'
    | '/customize/'
    | '/photobooth/'
    | '/api/public/jobs/cleanup-error-logs'
    | '/api/public/jobs/generate-weekly-challenges'
    | '/api/public/jobs/process-leaderboard-rewards'
    | '/api/public/jobs/send-admin-alert'
    | '/api/public/jobs/sync-health-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminChatRoute: typeof AdminChatRoute
  AuthRoute: typeof AuthRoute
  CollectionRoute: typeof CollectionRoute
  EmpireRoute: typeof EmpireRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MessagesRoute: typeof MessagesRoute
  PortalRoute: typeof PortalRoute
  RelationshipsRoute: typeof RelationshipsRoute
  StatsRoute: typeof StatsRoute
  CatkingActivityRoute: typeof CatkingActivityRoute
  CatkingAiMetricsRoute: typeof CatkingAiMetricsRoute
  CatkingAnnouncementsRoute: typeof CatkingAnnouncementsRoute
  CatkingBattlePassRoute: typeof CatkingBattlePassRoute
  CatkingConfigRoute: typeof CatkingConfigRoute
  CatkingDashboardRoute: typeof CatkingDashboardRoute
  CatkingDocsRoute: typeof CatkingDocsRoute
  CatkingErrorsRoute: typeof CatkingErrorsRoute
  CatkingGameRepairRoute: typeof CatkingGameRepairRoute
  CatkingMessagesRoute: typeof CatkingMessagesRoute
  CatkingModerationRoute: typeof CatkingModerationRoute
  CatkingNotificationsRoute: typeof CatkingNotificationsRoute
  CatkingPayloadValidatorRoute: typeof CatkingPayloadValidatorRoute
  CatkingProfilesRoute: typeof CatkingProfilesRoute
  CatkingSaveRecoveryRoute: typeof CatkingSaveRecoveryRoute
  CatkingScheduledJobsRoute: typeof CatkingScheduledJobsRoute
  CatkingSecurityRoute: typeof CatkingSecurityRoute
  CatkingSettingsRoute: typeof CatkingSettingsRoute
  CatkingStatsRoute: typeof CatkingStatsRoute
  CatkingTelemetryRoute: typeof CatkingTelemetryRoute
  CatkingTestsRoute: typeof CatkingTestsRoute
  CatkingTrackingRoute: typeof CatkingTrackingRoute
  CatkingTutorialRoute: typeof CatkingTutorialRoute
  CatkingUsersRoute: typeof CatkingUsersRoute
  CatkingWinstonRoute: typeof CatkingWinstonRoute
  CustomizeCatIdRoute: typeof CustomizeCatIdRoute
  PhotoboothCatIdRoute: typeof PhotoboothCatIdRoute
  CatkingIndexRoute: typeof CatkingIndexRoute
  CustomizeIndexRoute: typeof CustomizeIndexRoute
  PhotoboothIndexRoute: typeof PhotoboothIndexRoute
  ApiPublicJobsCleanupErrorLogsRoute: typeof ApiPublicJobsCleanupErrorLogsRoute
  ApiPublicJobsGenerateWeeklyChallengesRoute: typeof ApiPublicJobsGenerateWeeklyChallengesRoute
  ApiPublicJobsProcessLeaderboardRewardsRoute: typeof ApiPublicJobsProcessLeaderboardRewardsRoute
  ApiPublicJobsSendAdminAlertRoute: typeof ApiPublicJobsSendAdminAlertRoute
  ApiPublicJobsSyncHealthCheckRoute: typeof ApiPublicJobsSyncHealthCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-chat': {
      id: '/admin-chat'
      path: '/admin-chat'
      fullPath: '/admin-chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire': {
      id: '/empire'
      path: '/empire'
      fullPath: '/empire'
      preLoaderRoute: typeof EmpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/': {
      id: '/catking/'
      path: '/catking'
      fullPath: '/catking/'
      preLoaderRoute: typeof CatkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/activity': {
      id: '/catking/activity'
      path: '/catking/activity'
      fullPath: '/catking/activity'
      preLoaderRoute: typeof CatkingActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/ai-metrics': {
      id: '/catking/ai-metrics'
      path: '/catking/ai-metrics'
      fullPath: '/catking/ai-metrics'
      preLoaderRoute: typeof CatkingAiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/announcements': {
      id: '/catking/announcements'
      path: '/catking/announcements'
      fullPath: '/catking/announcements'
      preLoaderRoute: typeof CatkingAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/battle-pass': {
      id: '/catking/battle-pass'
      path: '/catking/battle-pass'
      fullPath: '/catking/battle-pass'
      preLoaderRoute: typeof CatkingBattlePassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/config': {
      id: '/catking/config'
      path: '/catking/config'
      fullPath: '/catking/config'
      preLoaderRoute: typeof CatkingConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/dashboard': {
      id: '/catking/dashboard'
      path: '/catking/dashboard'
      fullPath: '/catking/dashboard'
      preLoaderRoute: typeof CatkingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/docs': {
      id: '/catking/docs'
      path: '/catking/docs'
      fullPath: '/catking/docs'
      preLoaderRoute: typeof CatkingDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/errors': {
      id: '/catking/errors'
      path: '/catking/errors'
      fullPath: '/catking/errors'
      preLoaderRoute: typeof CatkingErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/game-repair': {
      id: '/catking/game-repair'
      path: '/catking/game-repair'
      fullPath: '/catking/game-repair'
      preLoaderRoute: typeof CatkingGameRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/messages': {
      id: '/catking/messages'
      path: '/catking/messages'
      fullPath: '/catking/messages'
      preLoaderRoute: typeof CatkingMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/moderation': {
      id: '/catking/moderation'
      path: '/catking/moderation'
      fullPath: '/catking/moderation'
      preLoaderRoute: typeof CatkingModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/notifications': {
      id: '/catking/notifications'
      path: '/catking/notifications'
      fullPath: '/catking/notifications'
      preLoaderRoute: typeof CatkingNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/payload-validator': {
      id: '/catking/payload-validator'
      path: '/catking/payload-validator'
      fullPath: '/catking/payload-validator'
      preLoaderRoute: typeof CatkingPayloadValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/profiles': {
      id: '/catking/profiles'
      path: '/catking/profiles'
      fullPath: '/catking/profiles'
      preLoaderRoute: typeof CatkingProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/save-recovery': {
      id: '/catking/save-recovery'
      path: '/catking/save-recovery'
      fullPath: '/catking/save-recovery'
      preLoaderRoute: typeof CatkingSaveRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/scheduled-jobs': {
      id: '/catking/scheduled-jobs'
      path: '/catking/scheduled-jobs'
      fullPath: '/catking/scheduled-jobs'
      preLoaderRoute: typeof CatkingScheduledJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/security': {
      id: '/catking/security'
      path: '/catking/security'
      fullPath: '/catking/security'
      preLoaderRoute: typeof CatkingSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/settings': {
      id: '/catking/settings'
      path: '/catking/settings'
      fullPath: '/catking/settings'
      preLoaderRoute: typeof CatkingSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/stats': {
      id: '/catking/stats'
      path: '/catking/stats'
      fullPath: '/catking/stats'
      preLoaderRoute: typeof CatkingStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/telemetry': {
      id: '/catking/telemetry'
      path: '/catking/telemetry'
      fullPath: '/catking/telemetry'
      preLoaderRoute: typeof CatkingTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/tests': {
      id: '/catking/tests'
      path: '/catking/tests'
      fullPath: '/catking/tests'
      preLoaderRoute: typeof CatkingTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/tracking': {
      id: '/catking/tracking'
      path: '/catking/tracking'
      fullPath: '/catking/tracking'
      preLoaderRoute: typeof CatkingTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/tutorial': {
      id: '/catking/tutorial'
      path: '/catking/tutorial'
      fullPath: '/catking/tutorial'
      preLoaderRoute: typeof CatkingTutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/users': {
      id: '/catking/users'
      path: '/catking/users'
      fullPath: '/catking/users'
      preLoaderRoute: typeof CatkingUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catking/winston': {
      id: '/catking/winston'
      path: '/catking/winston'
      fullPath: '/catking/winston'
      preLoaderRoute: typeof CatkingWinstonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/': {
      id: '/customize/'
      path: '/customize'
      fullPath: '/customize/'
      preLoaderRoute: typeof CustomizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/$catId': {
      id: '/customize/$catId'
      path: '/customize/$catId'
      fullPath: '/customize/$catId'
      preLoaderRoute: typeof CustomizeCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photobooth/': {
      id: '/photobooth/'
      path: '/photobooth'
      fullPath: '/photobooth/'
      preLoaderRoute: typeof PhotoboothIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photobooth/$catId': {
      id: '/photobooth/$catId'
      path: '/photobooth/$catId'
      fullPath: '/photobooth/$catId'
      preLoaderRoute: typeof PhotoboothCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/cleanup-error-logs': {
      id: '/api/public/jobs/cleanup-error-logs'
      path: '/api/public/jobs/cleanup-error-logs'
      fullPath: '/api/public/jobs/cleanup-error-logs'
      preLoaderRoute: typeof ApiPublicJobsCleanupErrorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/generate-weekly-challenges': {
      id: '/api/public/jobs/generate-weekly-challenges'
      path: '/api/public/jobs/generate-weekly-challenges'
      fullPath: '/api/public/jobs/generate-weekly-challenges'
      preLoaderRoute: typeof ApiPublicJobsGenerateWeeklyChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/process-leaderboard-rewards': {
      id: '/api/public/jobs/process-leaderboard-rewards'
      path: '/api/public/jobs/process-leaderboard-rewards'
      fullPath: '/api/public/jobs/process-leaderboard-rewards'
      preLoaderRoute: typeof ApiPublicJobsProcessLeaderboardRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/send-admin-alert': {
      id: '/api/public/jobs/send-admin-alert'
      path: '/api/public/jobs/send-admin-alert'
      fullPath: '/api/public/jobs/send-admin-alert'
      preLoaderRoute: typeof ApiPublicJobsSendAdminAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/sync-health-check': {
      id: '/api/public/jobs/sync-health-check'
      path: '/api/public/jobs/sync-health-check'
      fullPath: '/api/public/jobs/sync-health-check'
      preLoaderRoute: typeof ApiPublicJobsSyncHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminChatRoute: AdminChatRoute,
  AuthRoute: AuthRoute,
  CollectionRoute: CollectionRoute,
  EmpireRoute: EmpireRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  MessagesRoute: MessagesRoute,
  PortalRoute: PortalRoute,
  RelationshipsRoute: RelationshipsRoute,
  StatsRoute: StatsRoute,
  CatkingActivityRoute: CatkingActivityRoute,
  CatkingAiMetricsRoute: CatkingAiMetricsRoute,
  CatkingAnnouncementsRoute: CatkingAnnouncementsRoute,
  CatkingBattlePassRoute: CatkingBattlePassRoute,
  CatkingConfigRoute: CatkingConfigRoute,
  CatkingDashboardRoute: CatkingDashboardRoute,
  CatkingDocsRoute: CatkingDocsRoute,
  CatkingErrorsRoute: CatkingErrorsRoute,
  CatkingGameRepairRoute: CatkingGameRepairRoute,
  CatkingMessagesRoute: CatkingMessagesRoute,
  CatkingModerationRoute: CatkingModerationRoute,
  CatkingNotificationsRoute: CatkingNotificationsRoute,
  CatkingPayloadValidatorRoute: CatkingPayloadValidatorRoute,
  CatkingProfilesRoute: CatkingProfilesRoute,
  CatkingSaveRecoveryRoute: CatkingSaveRecoveryRoute,
  CatkingScheduledJobsRoute: CatkingScheduledJobsRoute,
  CatkingSecurityRoute: CatkingSecurityRoute,
  CatkingSettingsRoute: CatkingSettingsRoute,
  CatkingStatsRoute: CatkingStatsRoute,
  CatkingTelemetryRoute: CatkingTelemetryRoute,
  CatkingTestsRoute: CatkingTestsRoute,
  CatkingTrackingRoute: CatkingTrackingRoute,
  CatkingTutorialRoute: CatkingTutorialRoute,
  CatkingUsersRoute: CatkingUsersRoute,
  CatkingWinstonRoute: CatkingWinstonRoute,
  CustomizeCatIdRoute: CustomizeCatIdRoute,
  PhotoboothCatIdRoute: PhotoboothCatIdRoute,
  CatkingIndexRoute: CatkingIndexRoute,
  CustomizeIndexRoute: CustomizeIndexRoute,
  PhotoboothIndexRoute: PhotoboothIndexRoute,
  ApiPublicJobsCleanupErrorLogsRoute: ApiPublicJobsCleanupErrorLogsRoute,
  ApiPublicJobsGenerateWeeklyChallengesRoute:
    ApiPublicJobsGenerateWeeklyChallengesRoute,
  ApiPublicJobsProcessLeaderboardRewardsRoute:
    ApiPublicJobsProcessLeaderboardRewardsRoute,
  ApiPublicJobsSendAdminAlertRoute: ApiPublicJobsSendAdminAlertRoute,
  ApiPublicJobsSyncHealthCheckRoute: ApiPublicJobsSyncHealthCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
